### ISSUE TITLE
npm WARN deprecated ionic-gulp-webpack-build@1.0.0: ionic-gulp-webpack-build has been renamed to ionic-gulp-webpack

### ISSUE THREAD

**Issue by nunoarruda** [driftyco/ionic-gulp-tasks#1]
<img width="566" alt="screen shot 2016-03-23 at 09 59 00" src="https://cloud.githubusercontent.com/assets/1189149/13973460/e82d4ea4-f0dd-11e5-8fb5-3a7e979710d6.png">

Was it really renamed or is this a mistake? Can't find nothing about ionic-gulp-webpack

**Comment by tlancina** [comment]
I must have forgotten to publish after switching the name over and deprecating the old one, thanks!
