### ISSUE TITLE
ES3 target support

### ISSUE THREAD

**Issue by evgeniynet** [driftyco/ionic-gulp-tasks#18]
Hi, 

thanks for posting great tool. I am a newby in ionic and I need to run my ionic 2 app on old android devices (2.2) with ecmascript 3 support.
Especially I got errors on "delete" methods which is reserved in es3,
is there is option how to specify target ES3 or use es3ify to have compatibility to older browsers?

Any help appreciated,
Eugene

**Comment by mhartington** [comment]
Hey, thanks for opening an issue.
We're not going to support Android 2.2 or ES3. 
Sorry, going to close this.
