### ISSUE TITLE
Include build:before

### ISSUE THREAD

**Issue by dylanvdmerwe** [driftyco/ionic-gulp-tasks#2]
Shouldn't this be added by default?

`gulp.task('build:before', ['build']);`

**Comment by dmackerman** [comment]
We have `gulp.task('build', buildWebpack);`

``` js
gulp.task('serve:before', ['fonts', 'watch']);
gulp.task('emulate:before', ['build']);
gulp.task('deploy:before', ['build']);

// we want to 'watch' when livereloading
var shouldWatch = argv.indexOf('-l') > -1 || argv.indexOf('--livereload') > -1;
gulp.task('run:before', [shouldWatch ? 'watch' : 'build']);
```

And all is well.

**Comment by dylanvdmerwe** [comment]
`ionic build android`

> WARN: No 'build:before' gulp task found!
> If your app requires a build step, you may want to ensure it runs before build.

I could not understand when I ran the build commands for ios and android why the ionic www platform folder was not updating. I added the build:before step into the gulp file and the solution updated correctly.

**Comment by tlancina** [comment]
Should be updated in the starters, thanks!
