### ISSUE TITLE
[browserify-typescript] Typings v1.0 default path

### ISSUE THREAD

**Issue by dzonatan** [driftyco/ionic-gulp-tasks#23]
After [typings 1.0 release](https://github.com/typings/typings/releases) the default path is changed from `typings/main.d.ts` to `typings/index.d.ts`.

At least warn developers about overriding `src` property if they use 1.x.

**Comment by arielweinberger** [comment]
Just letting you guys know, I have submitted a pull request for the browserify-typescript gulp task. It should be reviewed and hopefully merged soon, and afterwards I will make the necessary changes in the app-base for all Ionic 2 starter and blank projects. Seems to fix the issue.

https://github.com/driftyco/ionic-gulp-tasks/pull/27

**Comment by mhartington** [comment]
This has been fixed in the 2.0.0 release of the gulp task. Please bump the version in your package.json and npm install
