### ISSUE TITLE
missing extensions in default options 

### ISSUE THREAD

**Issue by sgireddy** [driftyco/ionic-gulp-tasks#29]
I am using ng2-cookies module and ended up with the following error:

ParseError: 'import' and 'export' may appear only with 'sourceType: module'

Fixed by adding .ts to extensions in default options. Please fix.

browserifyOptions: {
    cache: {},
    packageCache: {},
    debug: true,
    extensions: ['.js', '.ts']
  },

**Comment by mhartington** [comment]
This is no longer a valid issue with the current setup and build system.
