### ISSUE TITLE
Offline compiler and tree shaking

### ISSUE THREAD

**Issue by Kobzol** [driftyco/ionic-gulp-tasks#48]
Is there any estimate when offline compiling and tree shaking might arrive for Ionic 2? Our Ionic 2 app currently starts very slowly.

**Comment by apparition47** [comment]
I'm looking forward to this feature too for the same reasons. There's lots of activity going on here:

https://github.com/driftyco/ionic/issues/6776
https://github.com/driftyco/ionic/issues/8061

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us! As you can see from the above linked issues we are hard at work on this at the moment. Also, if you want to follow the progress you can check out the master branch of the [ionic repo](https://github.com/driftyco/ionic). Thanks!
