### ISSUE TITLE
browserify-es2015: SyntaxError: Unexpected token when using types in JS

### ISSUE THREAD

**Issue by iignatov** [driftyco/ionic-gulp-tasks#6]
> **NOTE:** I'm not sure if types are supported out of the box in Ionic 2 JS projects.
#### Short description of the problem:

When using types in a Ionic 2 JS project the following error is thrown:

```
SyntaxError: C:/Projects/Test/app/app.js: Unexpected token (12:9) while parsing file: C:\Projects\Test\app\app.js
```
#### What behavior are you expecting?

If types are supported in JS projects then the code should be converted to a valid JS code and executed.

**Steps to reproduce:**
1. Create new JS project using `ionic start Test --v2`.
2. Add a class property and some type.
3. Add a type to the `platform` parameter of the constructor.
4. Try to run the app in the browser, i.e. `ionic serve`.
5. Observe the error that breaks the serve task.

``` js
// app.js
import 'es6-shim';
import {App, Platform} from 'ionic-angular';
import {StatusBar} from 'ionic-native';
import {TabsPage} from './pages/tabs/tabs';


@App({
  template: '<ion-nav [root]="rootPage"></ion-nav>',
  config: {} // http://ionicframework.com/docs/v2/api/config/Config/
})
export class MyApp {
  testing: string;

  static get parameters() {
    return [[Platform]];
  }

  constructor(platform: Platform) {
    this.rootPage = TabsPage;

    platform.ready().then(() => {
      // Okay, so the platform is ready and our plugins are available.
      // Here you can do any higher level native things you might need.
      StatusBar.styleDefault();
    });
  }
}
```

**Other information:** (e.g. stacktraces, related issues, stackoverflow links, forum links, etc)

https://forum.ionicframework.com/t/cant-start-android-app-after-updating-to-beta-4/48795/3
https://forum.ionicframework.com/t/syntaxerror-unexpected-token-how-is-that-possible/48717
https://forum.ionicframework.com/t/error-in-http-map-function-on-beta-4/48811

**Run `ionic info` from terminal/cmd prompt:** (paste output below)

```
Your system information:

Cordova CLI: 6.1.1
Gulp version:  CLI version 1.2.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-beta.4
Ionic CLI Version: 2.0.0-beta.24
Ionic App Lib Version: 2.0.0-beta.14
OS: Windows 8.1
Node Version: v5.8.0
```

**Comment by tlancina** [comment]
Hey thanks for the issue, types are only supported in TypeScript projects.  The JS projects used the TypeScript compiler in the past, so types would magically work, which is possibly why there is some confusion there, but they are not valid JS syntax.

**Comment by iignatov** [comment]
Thanks for the clarification!

I thought that the types in JS projects were supported for compatibility with Flow, because I've seen various JS-examples with types in the forum, but it's good to know that it was just a side effect of the usage of the TypeScript compiler in JS projects before `beta.4`.

Here is a workaround in case that someone wants to use the type annotations and class properties in a Ionic 2 JS project:
- update the `gulpfile.js` file as follows:

``` javascript
// Change: `buildBrowserify({ watch: true }).on('end', done);` to:
buildBrowserify({
  babelifyOptions: {
    plugins: [
      'transform-decorators-legacy',
      'transform-class-properties',
      'transform-flow-strip-types'
    ]
  },
  watch: true
}).on('end', done);
```
- install the needed npm packages:

```
npm install babel-plugin-transform-class-properties --save
npm install babel-plugin-transform-flow-strip-types --save
```
